"""braid: braiding signals into ranks."""

__version__ = "0.1.0"

from braid.core.registry import registry  # noqa: F401  -- exposed as braid.registry
from braid.core.capability import capability  # noqa: F401

# Eagerly import every category module so all concretes are registered.
from braid import (  # noqa: F401
    core,
    data,
    datasource,
    datasink,
    sessionizer,
    splitter,
    metadata,
    verbalizer,
    template,
    truncation,
    tokenizer,
    tokencounter,
    backbone,
    rewards,
    catalogstore,
    indexer,
    embedding,
    loss,
    optimizer,
    scheduler,
    checkpoint,
    regularizer,
    tracker,
    phase,
    miner,
    curriculum,
    batcher,
    server,
    cache,
    auth,
    ratelimit,
    reqpre,
    resppost,
    eval,
    metrics,
    drift,
    driftresponse,
    tracing,
    log,
    secret,
    router,
    cflog,
    bandit,
    rankaggregator,
    quantizer,
    serving,
    training,
    monitoring,
    testing,
    obsgen,
)
